title: Yaakov's blog
description: >-
  Packaging (mis)adventures across Fedora Linux and open source software
author: Yaakov Selkowitz
github_username:  yselkowitz
linkedin_username: yselkowitz
# Build settings
theme: minima
plugins:
  - jekyll-feed
minima:
  skin: dark
  date_format: "%d %b %Y"
