title: Yaakov's blog
description: >-
  Packaging (mis)adventures across Fedora Linux and open source software
author:
  name: Yaakov Selkowitz
#  email:

# Build settings
#theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
minima:
  skin: auto
  date_format: "%d %b %Y"
  social_links:
    - { platform: github,   user_url: "https://github.com/yselkowitz/" }
    - { platform: gitlab,   user_url: "https://gitlab.com/yselkowitz1/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yselkowitz/" }
